language: objective-c
osx_image: xcode7.2
xcode_project: Swift/Adhan.xcodeproj
xcode_scheme: AdhanTests
xcode_sdk: iphonesimulator
before_install:
  - brew update
  - brew install python3
  - pip3 install codecov
install:
  - pip3 install tox
before_script:
  - npm install -g node-qunit-phantomjs
script:
  - xctool -project Swift/Adhan.xcodeproj -scheme AdhanTests -sdk iphonesimulator build test
  - JavaScript/Tests/runtests
  - node-qunit-phantomjs JavaScript/Tests/tests.html
  - cd $TRAVIS_BUILD_DIR/Python && tox --hashseed 0
after_success:
  - cd $TRAVIS_BUILD_DIR/Python && tox -e coverage-report
  - cd $TRAVIS_BUILD_DIR/Python && codecov
notifications:
  email: false
