language: objective-c
osx_image: xcode7.2
xcode_project: Swift/Adhan.xcodeproj
xcode_scheme: AdhanTests
xcode_sdk: iphonesimulator
install:
  - brew update && brew install python3
before_script:
  - npm install -g node-qunit-phantomjs
script:
  - xctool -project Swift/Adhan.xcodeproj -scheme AdhanTests -sdk iphonesimulator build test
  - JavaScript/Tests/runtests
  - node-qunit-phantomjs JavaScript/Tests/tests.html
  - cd Python && python setup.py test
python: 3.5
