language: objective-c
osx_image: xcode7.2
xcode_project: Swift/Adhan.xcodeproj
xcode_scheme: AdhanTests
xcode_sdk: iphonesimulator
script:
- xctool -project Swift/Adhan.xcodeproj -scheme AdhanTests -sdk iphonesimulator build test
- mvn -f java/pom.xml clean test
