language: python
# osx_image: xcode7.2
# xcode_project: Swift/Adhan.xcodeproj
# xcode_scheme: AdhanTests
# xcode_sdk: iphonesimulator
# before_script:
 # - npm install -g node-qunit-phantomjs
script:
 # - xctool -project Swift/Adhan.xcodeproj -scheme AdhanTests -sdk iphonesimulator build test
 # - JavaScript/Tests/runtests
 # - node-qunit-phantomjs JavaScript/Tests/tests.html
 - nosetests ./Python
python: 3.5
install:
  - pip install ./Python
